version: '3'
services:
  api:
    # コンテナ名
    container_name: susutto-api
    build:
      #docker buildコマンドを実行した場所(composeの場合は up等)
      context: ./
    # ホスト側ポート番号:コンテナ側ポート番号　
    ports:
      - '8010:8010'
    # 環境変数の設定
    environment:
      - DEBUG=app:*
    #起動時のコンテナ内のカレントディレクトリ
    working_dir: /app
    env_file:
      - .env
